apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appConfigmap.name }}
data:
  brave.yaml: |
   owner: 'brave'
   repo: 'brave-browser'
   base: 'master'
   head: '0.72.x'
   apiV: '2022-11-28'
   accept: 'application/vnd.github+json'
  
  spring.yaml: |
   owner : 'spring-projects'
   repo : 'spring-framework'
   base : '3.0.x'
   head : '3.1.x'
   apiV: '2022-11-28'
   accept: 'application/vnd.github+json'

  hibernate.yaml: |
   owner : 'hibernate'
   repo : 'hibernate-reactive'
   base : '1.0'
   head : '1.1'
   apiV: '2022-11-28'
   accept: 'application/vnd.github+json'